Controllers/PocetnaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meritokrat2.Controllers
{
    public class PocetnaController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meritokrat</title>
    <link href="~/Content/Styles/MyStyle.css" rel="stylesheet" />
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Dosis:600|Roboto+Slab:300" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="font-family: 'Roboto Slab', serif; font-size: 1.3em; color:#fff;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <b>
                    @Html.ActionLink("Meritokrat", "Index", "Pocetna", new { area = "" }, new { @class = "navbar-brand" })
                </b>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Akademija", "Index", "Akademija")</li>
                    <li>@Html.ActionLink("Rezultati", "Index", "Rezultati")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="font-family: 'Dosis', serif; font-size: 3.9rem;">
        @RenderBody()
        @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<style>
    body {
        background-image: url("../../Content/Images/bg.png");
        background-color: #cccccc;
    }

    #modBtn {
        position: fixed; /* Fixed/sticky position */
        bottom: 20px; /* Place the button at the bottom of the page */
        right: 30px; /* Place the button 30px from the right */
        z-index: 99; /* Make sure it does not overlap */
        border: none; /* Remove borders */
        outline: none; /* Remove outline */
        color: white; /* Text color */
        cursor: pointer; /* Add a mouse pointer on hover */
        padding: 15px; /* Some padding */
        border-radius: 50%; /* Rounded corners */
        font-size: 18px; /* Increase font size */
        width: 60px;
        height: 60px;
    }
</style>

@if (User != null && User.IsInRole("Administrator") || User.IsInRole("Moderator"))
{
    <a href="@Url.Action("Index", "Moderator")" class="btn btn-primary animated heartBeat delay-2s slow" id="modBtn">
        <i class="fas fa-sliders-h" style="font-size:1.8em;"></i>
    </a>
}