Models/AppModels/Kviz/Pitanje.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Meritokrat2.Models.AppModels.Kviz
{
    public class Pitanje
    {
        public Pitanje()
        {
            Odgovori = new List<Odgovor>();
        }

        [Key]
        public int PitanjeId { get; set; }
        public int IdKviz { get; set; }
        public PitanjeType Tip { get; set; }
        public string TekstPitanja { get; set; }
        public virtual ICollection<Odgovor> Odgovori { get; set; }
        public int Vrijednost { get; set; } = 1;

        internal static bool JeliTocnoOdgovoreno(Pitanje pitanje, Odgovor odgovor)
        {
            //ako je pitanje sa jednim tocnim odgovorom
            if (pitanje.Tip == PitanjeType.Jedan_tocan)
            {
                //dohvacamo tocan odgovore
                var tocanOdgovor = pitanje.Odgovori.Where(x => x.Tocan).Single();

                //vracamo true ako je proslijeden odgovor jednak tocnom odgovoru.. inace false
                return tocanOdgovor.OdgovorId == odgovor.OdgovorId;
            }

            //ako je pitanje sa vise tocnih odgovora
            else if (pitanje.Tip == PitanjeType.Vise_tocnih)
            {
                //prvo razdijelimo odgovore (httppost ih salje odvojene zarezom)
                var _odgovori = odgovor.TekstOdgovora.Split(',');

                //dohvacamo tocne odgovore
                var tocniOdgovori = pitanje.Odgovori.Where(x => x.Tocan);

                //---------------------
                //PROVJERI RADI LI OVO
                //---------------------
                //prolazimo kroz sve tocne odgovore poslanog pitanja iz parametra
                //ako se medu poslanim odgovorima iz parametra ne nalazi tocan odgovor
                //vraca se false.. inace true
                foreach (var tocanOdgovor in tocniOdgovori)
                {
                    if (!_odgovori.ToList().Contains(tocanOdgovor.TekstOdgovora))
                    {
                        //vracamo false ako ne sadrzi tocan odgovor
                        return false;
                    }
                }
                return true;
            }

            //ako je pitanje nadopune
            else if (pitanje.Tip == PitanjeType.Nadopuni)
            {
                //dohvacamo moguce tocne odgovore
                var tocniOdgovori = pitanje.Odgovori.Where(x => x.Tocan);
                foreach (var tocanOdgovor in tocniOdgovori)
                {
                    if (tocanOdgovor.TekstOdgovora == odgovor.TekstOdgovora)
                    {
                        //vracamo true ako sadrzi tocan odgovor
                        return true;
                    }
                }
                //vracamo false ako ne sadrzi tocan odgovor
                return false;
            }

            //baci gresku ako je pitanje broken
            throw new Exception("Nepoznat tip pitanja.");
        }

        public override bool Equals(object obj)
        {
            var pitanje = obj as Pitanje;
            return pitanje.PitanjeId == PitanjeId && pitanje.Tip == Tip && TekstPitanja == TekstPitanja;
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
    }

    public enum PitanjeType
    {
        Jedan_tocan,
        Vise_tocnih,
        Nadopuni
    }
}

Controllers/KvizController.cs
using Meritokrat2.Models.AppModels;
using Meritokrat2.Models.AppModels.Kviz;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meritokrat2.Controllers
{
    public class KvizController : MyController
    {
        [Authorize(Roles = "Administrator,Moderator")]
        public ActionResult Pregled(int id)
        {
            //id je id lekcije za koju se dohvaca kviz
            var lekcija = Repository.GetLekcija(id);
            ViewBag.Lekcija = lekcija;

            var kviz = Repository.GetKviz(lekcija.IdKviz);
            ViewBag.Kviz = kviz;
            List<Pitanje> pitanja = null;
            if (kviz != null)
            {
                pitanja = Repository.GetPitanjaZaKviz(kviz.KvizId);
            }
            return View(pitanja);
        }

        [HttpGet]
        public ActionResult Dodaj(int id)
        {
            var lekcija = Repository.GetLekcija(id);
            ViewBag.Lekcija = lekcija;
            return View();
        }

        [HttpPost]
        public ActionResult Dodaj(int LekcijaId, int dummy = 0)
        {
            var keys = Request.Form.AllKeys;

            List<Pitanje> pitanja = new List<Pitanje>();
            List<int> doneNumbers = new List<int>();

            var kviz = Repository.GetKvizForLekcija(LekcijaId);
            
            foreach (var key in keys)
            {
                if (key.Contains("_"))
                {
                    string[] splitKey = key.Split('_');
                    int odgovorBroj = int.Parse(splitKey[1]);
                    if (!doneNumbers.Contains(odgovorBroj))
                    {
                        String tekstPitanja = Request.Form[keys.Where(x => x == $"tekst_{odgovorBroj}").FirstOrDefault().Trim()];
                        PitanjeType tip = ((PitanjeType)Enum.Parse(typeof(PitanjeType), Request.Form[keys.Where(x => x == $"tip_{odgovorBroj}").FirstOrDefault()]));

                        Pitanje pitanje = new Pitanje()
                        {
                            TekstPitanja = tekstPitanja,
                            Tip = tip,
                            IdKviz = kviz.KvizId,
                            Vrijednost = 1 //dodati podrsku za vrijednost
                        };
                        Repository.AddPitanje(pitanje);

                        String _odgovori = Request.Form[keys.Where(x => x == $"odgovor_{odgovorBroj}").FirstOrDefault()];
                        //ako je više odgovora
                        if (_odgovori.Contains("\r\n"))
                        {
                            string[] odgovori = _odgovori.Split(new char[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
                            foreach (var _odgovor in odgovori)
                            {
                                DodajOdgovor(pitanje, _odgovor);
                            }
                        }
                        //ako je samo jedan odgovor
                        else
                        {
                            DodajOdgovor(pitanje, _odgovori);
                        }
                        doneNumbers.Add(odgovorBroj);
                    }
                }
            }
            Repository.AddAktivnost(new Aktivnost(User.Identity.GetUserId(), $"Dodaje pitanja za lekciju (id: {LekcijaId}).", true));
            return RedirectToAction("Pregled", new { id = LekcijaId });
        }

        private void DodajOdgovor(Pitanje pitanje, string _odgovor)
        {
            Odgovor odgovor = new Odgovor();
            odgovor.IdPitanje = pitanje.PitanjeId;
            if (_odgovor.Trim().Length > 0)
            {
                if (_odgovor[0] == '*')
                {
                    odgovor.Tocan = true;
                    odgovor.TekstOdgovora = _odgovor.Substring(1);
                }
                else
                {
                    odgovor.Tocan = false;
                    odgovor.TekstOdgovora = _odgovor;
                }
                if (pitanje.Tip == PitanjeType.Nadopuni)
                {
                    odgovor.Tocan = true;
                }
                Repository.AddOdgovor(odgovor);
            }
        }


    }
}

Controllers/PitanjeController.cs
using Meritokrat2.Models.AppModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meritokrat2.Controllers
{
    [Authorize(Roles = "Administrator,Moderator")]
    public class PitanjeController : MyController
    {
        [HttpGet]
        public ActionResult Izbrisi(int id, int lekcijaId)
        {
            Repository.AddAktivnost(new Aktivnost(User.Identity.GetUserId(), $"Briše pitanje (id: {id})", true));
            Repository.DeletePitanje(id);
            return RedirectToAction("pregled", "kviz", new { id = lekcijaId });
        }

        [HttpGet]
        public ActionResult Uredi(int id, int lekcijaId)
        {
            Repository.AddAktivnost(new Aktivnost(User.Identity.GetUserId(), $"Uređuje pitanje (id: {id})", true));
            throw new NotImplementedException();
            //Repository.DeletePitanje(id);
            return RedirectToAction("pregled", "kviz", new { id = lekcijaId });
        }
    }
}

Views/Pitanje/Uredi.cshtml
@model Meritokrat2.Models.AppModels.Kviz.Pitanje
@using Meritokrat2.Models.AppModels;

@{
    ViewBag.Title = "Uređivanje pitanja";
    Lekcija lekcija = ViewBag.Lekcija as Lekcija;
}

<div class="holder" style="min-height: 600px;font-size: 0.66em;">
    @if (lekcija != null)
    {
        <div>
            <h3 style="font-size: 1em;">
                Uređivanje pitanja
            </h3>
        </div>
    }
    <form action="@Url.Action("Dodaj", "Kviz")" method="post">
        <input type="hidden" name="LekcijaId" value="@lekcija.LekcijaId" />
        <div class="col-md-7 col-sm-6">
            <div id="pitanja">

            </div>
            <div style="text-align: right;">
                <button type="button" id="dodajPitanje" class="btn btn-primary" style="font-size: 0.70em; margin-bottom: 5px; width:100%">
                    <i class="fas fa-plus" style="font-size:0.85em; margin-right: 3.5px;"></i>
                    Dodaj novo pitanje
                </button>
            </div>
        </div>
        <div class="col-md-5 col-sm-6">
            <div class="spremiHolder">
                <div style="background-color: rgba(226, 226, 226, 0.12); padding: 10px; font-size: 0.66em; margin-bottom: 10px;">
                    <input type="submit" value="Spremi kviz" class="btn btn-success" style="width: 100%;">
                </div>
            </div>
            <div class="spremiHolder">
                <div style="background-color: rgba(226, 226, 226, 0.12); padding: 10px; font-size: 0.66em;">
                    <h3 style="margin: 0 0 7px">
                        <i class="fas fa-info-circle" style="font-size:0.75em; margin-right: 3.5px;"></i>
                        Upute
                    </h3>
                    <p>Prilikom unosa pitanja <b>unesite sva polja</b>.</p>
                    <p>Prilikom unošenja odgovora, odgovore odvajajte <b>prelaskom u novi red</b>.</p>
                    <p>Kod <b>"1 točan"</b> unesite sve odgovore te ispred točnog odgovora dodajte * (zvjezdicu).</p>
                    <p>Kod <b>"Više točnih"</b> unesite sve odgovore te ispred točnih odgovora dodajte * (zvjezdice).</p>
                    <p>Kod <b>"Nadopuni"</b> unesite sve moguće točne odgovore (bez zvjezdice) odvojene novim redom. Odgovori <b>nisu</b> osjetljivi na velika i mala slova.</p>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>

<a href="@Url.Action("pregled", "kviz", new { id =lekcija.LekcijaId })" class="btn btn-warning" style="font-size: 0.36em;">
    <i class="fas fa-angle-left" style="font-size:0.85em; margin-right: 3.5px;"></i>
    Natrag
</a>

@Scripts.Render("~/bundles/jquery")

<script>
    let trenutnaPitanja = 1;
    $(document).ready(function () {
        addPitanje();
        $("#dodajPitanje").click(function () {
            addPitanje();
        });
    });

    function addPitanje() {
        let pitanjeTemplate = document.querySelector("#pitanjeTemplate");
        let pitanje = document.importNode(pitanjeTemplate.content, true);

        let brojPitanja = trenutnaPitanja++;
        pitanje.getElementById("tekst").name = "tekst_" + brojPitanja;
        pitanje.getElementById("odgovor").name = "odgovor_" + brojPitanja;
        pitanje.getElementById("tip1").name = "tip_" + brojPitanja;
        pitanje.getElementById("tip2").name = "tip_" + brojPitanja;
        pitanje.getElementById("tip3").name = "tip_" + brojPitanja;

        pitanje.getElementById("tip1").id = "tipId_1_" + brojPitanja;
        pitanje.getElementById("tip2").id = "tipId_2_" + brojPitanja;
        pitanje.getElementById("tip3").id = "tipId_3_" + brojPitanja;

        pitanje.getElementById("label1").htmlFor = "tipId_1_" + brojPitanja;
        pitanje.getElementById("label2").htmlFor = "tipId_2_" + brojPitanja;
        pitanje.getElementById("label3").htmlFor = "tipId_3_" + brojPitanja;

        pitanje.getElementById("izbrisiPitanje").addEventListener("click", function (event) {
            let deleteCardIcon = event.target;
            let card = deleteCardIcon.parentElement.parentElement;
            card.remove();
        });

        document.querySelector("#pitanja").appendChild(pitanje);

        var el = document.getElementsByClassName("holder")[0];
    }

</script>

<template id="pitanjeTemplate" class="font">
    <div style="margin-bottom: 5px;">
        <div id="pitanjeid" style="background-color: rgba(112, 112, 112, 0.21);padding: 13px;">
            <span style="font-size: 0.77em;">Pitanje</span>
            <textarea id="tekst" name="name" value="" placeholder="Tekst pitanja" class="form-control input-block-level" style="width:700px;"></textarea>
            <div class="switch-field">
                <input type="radio" id="tip1" name="switch_3" value="Jedan_tocan" checked />
                <label id="label1">1 točan</label>
                <input type="radio" id="tip2" name="switch_3" value="Vise_tocnih" />
                <label id="label2">Više točnih</label>
                <input type="radio" id="tip3" name="switch_3" value="Nadopuni" />
                <label id="label3">Nadopuni</label>
            </div>
            <textarea id="odgovor" name="name" value="" placeholder="Unesite odgovore odvojene novim redom
Ispred točnog odgovora stavite * (zvjezdicu)" class="form-control input-block-level" style="width:700px; height: 14vh;"></textarea>
            <div style="padding: 7px 0 0; text-align: right;">
                <button type="button" id="izbrisiPitanje" class="btn btn-danger" style="font-size: 0.60em;">
                    <i class="fas fa-trash-alt" style="font-size:0.85em; margin-right: 3.5px;"></i>
                    Izbriši pitanje
                </button>
            </div>
        </div>
    </div>
</template>

<style>
    .holder {
        font-family: 'Roboto Slab';
        color: #fff;
    }

    .font {
        font-family: 'Roboto Slab';
        color: #fff;
        font-size: 0.66em;
    }

    .col-sm-6 {
        padding: 0 !important;
    }

    h3 {
        margin-top: 5px;
        margin-bottom: 8px;
    }

    .spremiHolder {
        padding: 0 10px;
    }

    @@media only screen and (max-width: 800px) {
        .spremiHolder {
            padding: 0;
        }
    }
</style>


<style>
    .switch-field {
        font-family: "Lucida Grande", Tahoma, Verdana, sans-serif;
        overflow: hidden;
        margin-top: 7px;
    }

    .switch-title {
        margin-bottom: 6px;
    }

    .switch-field input {
        position: absolute !important;
        clip: rect(0, 0, 0, 0);
        height: 1px;
        width: 1px;
        border: 0;
        overflow: hidden;
    }

    .switch-field label {
        float: left;
    }

    .switch-field label {
        display: inline-block;
        width: 33.3333333%;
        background-color: #e4e4e4;
        color: rgba(0, 0, 0, 0.6);
        font-size: 14px;
        font-weight: normal;
        text-align: center;
        text-shadow: none;
        padding: 6px 14px;
        border: 1px solid rgba(0, 0, 0, 0.2);
        -webkit-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3), 0 1px rgba(255, 255, 255, 0.1);
        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3), 0 1px rgba(255, 255, 255, 0.1);
        -webkit-transition: all 0.1s ease-in-out;
        -moz-transition: all 0.1s ease-in-out;
        -o-transition: all 0.1s ease-in-out;
        transition: all 0.1s ease-in-out;
    }

        .switch-field label:hover {
            cursor: pointer;
        }

    .switch-field input:checked + label {
        background-color: #3e7ab7;
        -webkit-box-shadow: none;
        box-shadow: none;
        color: #fff;
    }

    .switch-field label:first-of-type {
        border-radius: 4px 0 0 4px;
    }

    .switch-field label:last-of-type {
        border-radius: 0 4px 4px 0;
    }
</style>