Models/AppModels/Lekcija.cs
using Meritokrat2.Data_Layer;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Meritokrat2.Models.AppModels
{
    public class Lekcija
    {
        public Lekcija()
        {
            MaxBodovi = 0;
            RijesenaPuta = 0;
        }

        public int LekcijaId { get; set; }
        [Required(ErrorMessage ="Naziv je obvezan")]
        public String Naziv { get; set; }

        [Display(Name = "Redni broj")]
        public int RBLekcije { get; set; } //redni broj lekcije
        [Required(ErrorMessage ="Datoteka je obvezna")]
        [Display(Name = "Video ID")]
        public Guid IdVideo { get; set; }

        [Display(Name = "Kviz ID")]
        public int IdKviz { get; set; } = 0;

        public Guid IdClanak { get; set; }
        public int RijesenaPuta { get; set; }

        [Display(Name = "Maks. bodova")]
        public int MaxBodovi { get; set; }
        public int Razred { get; set; }

        public String GetVideoUrl()
        {
            return $"{IdVideo}.mp4";
        }

        public String Prosjek
        {
            get
            {
                return RepoFactory.GetRepo().GetProsjekLekcije(this.LekcijaId);
            }
        }
    }
}

Controllers/AkademijaController.cs
using Meritokrat2.Models.AppModels;
using Meritokrat2.Models.AppModels.Kviz;
using Meritokrat2.Models.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace Meritokrat2.Controllers
{
    [UcenikAuthorize]
    public class AkademijaController : MyController
    {
        public ActionResult Index()
        {
            var ucenik = Repository.GetUcenik(1);
            ViewBag.Ucenik = ucenik;

            var lekcije = Repository.GetRijeseneLekcije(ucenik.UcenikId).ToList();
            ViewBag.Lekcije = lekcije;
            ViewBag.SljedecaLekcija = Repository.GetSljedecaLekcijaZaUcenika(ucenik.UcenikId);
            return View();
        }

        [System.Web.Http.HttpGet]
        public ActionResult Igraj()
        {
            var ucenik = Repository.GetUcenik(1);
            if (ucenik.MozeIgrati())
            {
                var lekcija = Repository.GetSljedecaLekcijaZaUcenika(ucenik.UcenikId);
                ViewBag.Lekcija = lekcija;
                var pitanja = Repository.Get5KvizPitanja(lekcija.IdKviz);
                ViewBag.Pitanja = pitanja;
                return View();
            }
            return RedirectToAction("Index");

        }

        [System.Web.Http.HttpPost]
        public ActionResult _Igraj(int lekcijaId)
        {
            var ucenik = Repository.GetUcenik(1);
            var keys = Request.Form.AllKeys;
            var bodovi = VerifyOdgovoriAndGetBodovi(keys);
            var ucenikLekcija = new UcenikLekcija()
            {
                IdLekcija = lekcijaId,
                IdUcenik = ucenik.UcenikId,
                Bodovi = bodovi,
                Biljeske = Request.Form["biljeske"],
                DatumRjesavanja = DateTime.Now
            };
            if (!Repository.GetRijeseneLekcije(ucenik.UcenikId).Contains(ucenikLekcija) && ucenik.MozeIgrati())
            {
                Repository.AddUcenikLekcija(ucenikLekcija);
                Repository.SetZadnjeOdigrano(ucenik.UcenikId);
                Repository.IncreaseLekcijaOdigrana(lekcijaId);
            }
            return RedirectToAction("Lekcija", new { id=lekcijaId, rjesena = true });
        }

        private int VerifyOdgovoriAndGetBodovi(string[] keys)
        {
            int bodovi = 0;
            foreach (var key in keys)
            {
                if (int.TryParse(key, out int _key))
                {
                    var pitanje = Repository.GetPitanje(_key);
                    if (pitanje.Tip == PitanjeType.Jedan_tocan)
                    {
                        var odgovori = Repository
                            .GetOdgovoriZaPitanje(pitanje.PitanjeId)
                            .Where(x => x.Tocan == true).FirstOrDefault();
                        if (int.TryParse(Request.Form[key], out int odgovorId))
                        {
                            if (odgovori?.OdgovorId == odgovorId)
                            {
                                bodovi += pitanje.Vrijednost;
                            }
                        }
                    }
                    else if (pitanje.Tip == PitanjeType.Vise_tocnih)
                    {
                        var odgovori = Repository
                            .GetOdgovoriZaPitanje(pitanje.PitanjeId)
                            .Where(x => x.Tocan == true);

                        var values = Request.Form[key];
                        var valuesCount = values.Count(c => c == ',');
                        if (odgovori.Count() == valuesCount + 1)
                        {
                            if (valuesCount > 0)
                            {
                                bool flag = false;
                                foreach (var _o in odgovori)
                                {
                                    if (!values.Contains(_o.OdgovorId.ToString()))
                                    {
                                        flag = true;
                                        break;
                                    }
                                }
                                if (flag == false)
                                {
                                    {
                                        bodovi += pitanje.Vrijednost;
                                    }
                                }
                            }
                        }
                    }
                    else if (pitanje.Tip == PitanjeType.Nadopuni)
                    {
                        var odgovori = Repository
                            .GetOdgovoriZaPitanje(pitanje.PitanjeId);

                        var tekst = Request.Form[key];
                        bool flag = false;
                        foreach (var _o in odgovori)
                        {
                            if (_o.TekstOdgovora.ToLower().Trim() == tekst.ToLower().Trim())
                            {
                                flag = true;
                                break;
                            }
                        }
                        if (flag == true)
                        {
                            bodovi += pitanje.Vrijednost;
                        }
                    }
                }

            }
            return bodovi;
        }

        public ActionResult Lekcija(int id, bool rjesena = false)
        {
            var ucenik = Repository.GetUcenik(1);
            if (Repository.MozeLiUcenikVidjetiLekciju(id, ucenik.UcenikId) == false)
            {
                var msg = new HttpResponseMessage(HttpStatusCode.Unauthorized) { ReasonPhrase = "Ne možete vidjeti ovu lekciju." };
                throw new HttpResponseException(msg);
            } else
            {
                var lekcija = Repository.GetLekcija(id);
                ViewBag.UcenikLekcija = Repository.GetUcenikLekcija(lekcija.LekcijaId, ucenik.UcenikId);
                ViewBag.Biljeske = Repository.GetBiljeskeZaUcenikaLekciju(ucenik.UcenikId, id);
                ViewBag.Rjesena = rjesena;
                return View(lekcija);
            }
        }
    }
}

Controllers/LekcijaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Meritokrat2.Models;
using Meritokrat2.Models.AppModels;
using Meritokrat2.Models.AppModels.Kviz;
using Microsoft.AspNet.Identity;

namespace Meritokrat2.Controllers
{
    [Authorize(Roles = "Administrator,Moderator")]
    public class LekcijaController : MyController
    {
        public ActionResult Index(int id)
        {
            return View(Repository.GetLekcije(id));
        }

        public ActionResult Pregled(int id)
        {
            Lekcija lekcija = Repository.GetLekcija(id);
            return View(lekcija);
        }

        #region Uređivanje lekcije
        [HttpGet]
        public ActionResult Uredi(int id)
        {
            var lekcija = Repository.GetLekcija(id);
            return View(lekcija);
        }

        [HttpPost]
        public ActionResult Uredi(Lekcija lekcija)
        {

            var _lekcija = Repository.GetLekcija(lekcija.LekcijaId);
            _lekcija.Naziv = lekcija.Naziv;

            if (_lekcija.IdVideo != Guid.Empty)
            {
                HandleUploadedVideo(Request, _lekcija.IdVideo.ToString());
            }
            else
            {
                _lekcija.IdVideo = (Guid)HandleUploadedVideo(Request);
            }
            Repository.UpdateLekcija(_lekcija);
            Repository.AddAktivnost(new Aktivnost(User.Identity.GetUserId(), $"Uređuje lekciju (id: {lekcija.LekcijaId}).", true));
            return RedirectToAction("Pregled", new { id = lekcija.LekcijaId });
        }
        #endregion

        #region Dodavanje Lekcije
        [HttpGet]
        public ActionResult Dodaj()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Dodaj(String Naziv, int Razred)
        {
            var lekcija = new Lekcija
            {
                Naziv = Naziv,
                Razred = Razred,
                MaxBodovi = 5
            };


            //primanje videa u uploadu
            Guid? videoGuid = HandleUploadedVideo(Request);
            if (videoGuid != null)
            {
                lekcija.IdVideo = (Guid)videoGuid;
            }
            Repository.AddLekcija(lekcija);

            //dodavanje kviza za lekciju
            Kviz kviz = new Kviz();
            Repository.AddKviz(kviz);
            Repository.SetKvizForLekcija(lekcija.LekcijaId, kviz.KvizId);
            Repository.AddAktivnost(new Aktivnost(User.Identity.GetUserId(), $"Dodaje lekciju (id: {lekcija.LekcijaId}).", true));

            return RedirectToAction("pregled", "lekcija", new { id = lekcija.LekcijaId });
        }

        private Guid? HandleUploadedVideo(HttpRequestBase request, string _guid = null)
        {
            if (request.Files[0] != null)
            {
                var httpPostedFile = request.Files[0];
                if (httpPostedFile != null && httpPostedFile.FileName.ToString() != "")
                {
                    string guid;
                    if (_guid == null)
                    {
                        guid = Guid.NewGuid().ToString();
                    } else
                    {
                        guid = _guid;
                    }

                    // Get the complete file path
                    var uploadFilesDir = System.Web.HttpContext.Current.Server.MapPath("~/Content/Videos");
                    if (!Directory.Exists(uploadFilesDir))
                    {
                        Directory.CreateDirectory(uploadFilesDir);
                    }
                    var fileSavePath = Path.Combine(uploadFilesDir, guid.ToString() + httpPostedFile.FileName.Substring(httpPostedFile.FileName.LastIndexOf('.')));

                    // Save the uploaded file to "UploadedFiles" folder
                    httpPostedFile.SaveAs(fileSavePath);
                    return Guid.Parse(guid);
                }
            }
            return null;
        }
        #endregion
    }
}

Controllers/RezultatiController.cs
using Meritokrat2.Models.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meritokrat2.Controllers
{
    [UcenikAuthorize]
    public class RezultatiController : MyController
    {
        public ActionResult Index()
        {
            ViewBag.Pojedinacni = Repository.GetRezultatiPojedinacno();
            ViewBag.PoSkolama = Repository.GetRezultatiPoSkolama();
            return View();
        }
    }
}

Views/Akademija/Igraj.cshtml
@using Meritokrat2.Models.AppModels;
@using Meritokrat2.Models.AppModels.Kviz;
@using Meritokrat2.Data_Layer;

@{

    Lekcija lekcija = ViewBag.Lekcija as Lekcija;
    List<Pitanje> pitanja = ViewBag.Pitanja as List<Pitanje>;
    ViewBag.Title = lekcija.Naziv;
    IRepo repo = RepoFactory.GetRepo();

}
<link href="~/Content/Styles/CustomBoxes.css" rel="stylesheet" />
<div class="holder">
    <div class="tab-content">
        <form action="@Url.Action("_Igraj", "Akademija")" method="post">
            @Html.AntiForgeryToken()
            <input type="hidden" name="lekcijaId" value="@lekcija.LekcijaId" />
            <div id="lekcija" class="tab-pane fade in active">
                <h2>@lekcija.Naziv</h2>
                <hr />
                <div class="col-md-8 col-sm-6">
                    <video controls="controls" style="width: 100%;">
                        <source src="~/Content/Videos/@lekcija.GetVideoUrl()" type="video/mp4" />
                    </video>
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="item">
                        <a data-toggle="pill" href="#kviz" class="btn btn-lg btn-primary" style="width: 100%;">Idi na kviz</a>
                    </div>
                    <div class="item" style="margin-top: 8px;font-family: 'Roboto Slab';">
                        <div style="margin-bottom: 5px;">
                            <h3 style="margin: 0;">Bilješke</h3>
                            <b>Bilješke ostaju spremljene.</b>
                        </div>
                        <textarea class="form-control" placeholder="Bilješke..." name="biljeske" maxlength="1000" rows="5"></textarea>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="kviz" class="tab-pane fade col-md-7 col-sm-6 k-holder" style="width: 100%;">
                <div>
                    <h3>@lekcija.Naziv - Kviz</h3>
                    <hr />
                    <div class="tab-content" style="font-family: 'Roboto Slab';padding-bottom: 20px;">
                        @for (int i = 0; i < pitanja.Count; i++)
                        {
                            var id = "lekcija" + i;
                            <div id="@id" class="tab-pane fade">
                                @{
                                    var forwardTab = $"#lekcija{i + 1}";
                                    var backwardTab = $"#lekcija{i - 1}";
                                    var odgovorName = $"odgovor{i}";
                                    var odgovori = repo.GetOdgovoriZaPitanje(pitanja[i].PitanjeId);

                                    if (pitanja[i].Tip == PitanjeType.Jedan_tocan)
                                    {
                                <div class="control-group">
                                    <h3 style="letter-spacing: 1.25px;"><b>@pitanja[i].TekstPitanja</b></h3>
                                    <br />
                                    @foreach (var odgovor in odgovori)
                                    {
                                        <label class="control control--radio">
                                            @odgovor.TekstOdgovora
                                            <input type="radio" name="@pitanja[i].PitanjeId" value="@odgovor.OdgovorId" />
                                            <div class="control__indicator"></div>
                                        </label>
                                    }
                                </div>
                                    }
                                    else if (pitanja[i].Tip == PitanjeType.Vise_tocnih)
                                    {
                                <div class="control-group">
                                    <h3 style="letter-spacing: 1.25px;"><b>@pitanja[i].TekstPitanja</b></h3>
                                    <br />

                                    @foreach (var odgovor in odgovori)
                                    {
                                        <label class="control control--checkbox">
                                            @odgovor.TekstOdgovora
                                            <input type="checkbox" name="@pitanja[i].PitanjeId" value="@odgovor.OdgovorId" />
                                            <div class="control__indicator"></div>
                                        </label>
                                    }
                                </div>

                                    }
                                    else if (pitanja[i].Tip == PitanjeType.Nadopuni)
                                    {
                                <div class="control-group">
                                    <h3 style="letter-spacing: 1.25px;"><b>@pitanja[i].TekstPitanja</b></h3>
                                    <br />
                                    <input type="text" class="form-control" name="@pitanja[i].PitanjeId" style="width: 100%;" placeholder="Odgovor..." />
                                </div>
                                    }
                                }
                                <hr />

                                @if (i != 0)
                                {
                                    <a data-toggle="pill" href="@backwardTab" class="btn btn-warning" style="float: left;">Natrag</a>
                                }
                                @if (i != pitanja.Count - 1)
                                {
                                    <a data-toggle="pill" href="@forwardTab" class="btn btn-info" style="float: right;">Dalje</a>
                                }
                                else
                                {
                                    <input type="submit" value="Pošalji kviz" class="btn btn-success" style="float: right;" />
                                }
                            </div>
                        }
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="clearfix"></div>

</div>

@Scripts.Render("~/bundles/jquery")


<script>
    $(function () {
        $('#lekcija0').addClass('in active');
    });
</script>

<style>
    .k-holder > div{
        background-color: rgba(255, 255, 255, 0.17);
        padding: 30px 20px !important;
    }

    .fade {
        display: none;
    }

    .in {
        display: block;
    }

    .holder {
        color: #fff;
        font-size: 0.46em;
    }

    .item {
        margin-left: 8px;
        background-color: rgba(255, 255, 255, 0.20);
        padding: 15px;
    }

    .col-sm-6 {
        padding-left: 0px !important;
        padding-right: 0px !important;
    }

    textarea.form-control {
        color: #000000;
        background-color: rgba(255, 255, 136, 0.8);
        min-width: 100%;
        -moz-border-radius: 0;
        -webkit-border-radius: 0;
        border-radius: 0;
        border: 0;
    }

        textarea.form-control:placeholder {
            color: dimgray;
            opacity: 1;
        }

        textarea.form-control:-ms-input-placeholder, textarea.form-control:-ms-input-placeholder {
            color: dimgray;
        }


    @@media only screen and (max-width: 800px) {
        .k-holder > div {
            background-color: rgba(0, 0, 0, 0.00);
            padding: 5px !important;
        }
        .item {
            margin-left: 0 !important;
        }
    }
</style>

Views/Akademija/Index.cshtml
@using Meritokrat2.Data_Layer
@using Meritokrat2.Models.AppModels
@using System.Threading;

@{
    ViewBag.Title = "Akademija znanja";
    Ucenik ucenik = ViewBag.Ucenik as Ucenik;
    List<UcenikLekcija> lekcije = ViewBag.Lekcije as List<UcenikLekcija>;
    Lekcija sljedecaLekcija = ViewBag.SljedecaLekcija as Lekcija;
    IRepo repo = RepoFactory.GetRepo();
}



<div class="holder" style="min-height: 800px; color: #fff; font-size: 0.45em;">
    <div class="col-md-12 col-sm-6 -holder animated flipInX" style="text-align: center; padding: 5px; margin-bottom: 5px;">
        <img style="width: 250px;" src="~/Content/Images/logo.png" />
    </div>

    <div class="">
        <div class="col-md-4 col-sm-12" >
            <div class="profile-holder" style="padding: 10px;">
                <div class="profile-holder2">
                    <img id="igracLik" src="~/Content/Images/az-prijava.png" />
                    <div style="display: inline-block; padding-left: 7px;">
                        @if (ucenik != null)
                        {
                            <b>Nadimak: </b>@ucenik.Nadimak
                            <br />
                            <b>Škola: </b>@ucenik.Skola
                            <br />
                            <b>Rezultat : </b>@ucenik.Rezultat
                        }
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index", "Rezultati")" class="col-md-12 col-sm-6 btn btn-warning btn-xl" style="margin-top: 7px;width: 100%;font-size: 1em;">
                <i class="fas fa-poll" style="font-size:0.85em; margin-right: 3.5px;"></i>
                Rezultati
            </a>
            @if (sljedecaLekcija != null)
            {

                if (ucenik.MozeIgrati())
                {
                    <div class="yes-holder" style="padding: 10px;margin-top: 52.5px;">
                        <div class="profile-holder2" style="text-align:center;">
                            <h4>Vaša lekcija za danas je spremna!</h4>
                            <h5>Klikom na gumb 'Kreni' pokrećete lekciju.</h5>
                        </div>
                    </div>
                }
                else
                {
                    <div class="no-holder" style="padding: 10px;margin-top: 52.5px;">
                        <div class="profile-holder2" style="text-align:center;">
                            <h4>Već ste odigrali igru za danas...</h4>
                            <h5>Pokušajte ponovno sutra.</h5>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="col-md-12 col-sm-12">
                    <div class="no-holder" style="padding: 10px;margin-top: 5.5px;">
                        <div class="profile-holder2" style="text-align:center;">
                            <h4>Nema sljedeće lekcije</h4>
                        </div>
                    </div>
                </div>
            }
            <div class="trenutna-lekcija-holder" style="padding: 10px;margin-top: 5.8px;">
                <div class="profile-holder2">

                    <h3 style="margin: 0 0 7px 0;">Sljedeća lekcija:</h3>
                    <video style="width: 100%;">
                        <source src="~/Content/Videos/@sljedecaLekcija.GetVideoUrl()" type="video/mp4" />
                    </video>
                    <div style="margin-bottom: 7px;padding: 5px; background-color: rgba(234, 234, 234, 0.17);" class="-holder">
                        <h4 style="display:inline;line-height: 34px;margin-left:5px;"><b>@sljedecaLekcija.RBLekcije. @sljedecaLekcija.Naziv</b></h4>
                        @if (ucenik.MozeIgrati())
                        {
                            @Html.ActionLink("Kreni", "Igraj", null, new { @class = "btn btn-success", style = "float: right; width: 100px;" })
                        }
                        else
                        {
                            <button class="btn btn-default disabled" style="float: right; width: 100px;">Igraj</button>

                        }
                    </div>

                </div>
            </div>

        </div>
        <div class="col-md-8 col-sm-6 lekcije">
            <div>
                <div class="lekcijeH">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <button type="button" class="btn btn-default btn-sm spoiler-trigger" data-toggle="collapse">Riješene lekcije</button>
                        </div>
                        <div class="panel-collapse collapse in">
                            <div class="panel-body">
                                <div class="scrollbar" style="width: 100%;" id="style-1">
                                    <div class="force-overflow">
                                        @if (lekcije.Count > 0)
                                        {
                                            foreach (var ul in lekcije)
                                            {
                                                var _lek = repo.GetLekcija(ul.IdLekcija);
                                                if (_lek != null)
                                                {
                                                    <div class="lekcija animated fadeIn">
                                                        <a href="@Url.Action("lekcija", "akademija", new { id = _lek.LekcijaId })">
                                                            <div style="display: inline-block;">
                                                                @_lek.RBLekcije. @_lek.Naziv
                                                            </div>
                                                            <div style="display: inline-block;float:right;">
                                                                <b>Bodovi: </b> @ul.Bodovi / @_lek.MaxBodovi
                                                                <i class="fas fa-star" style="font-size:0.85em; margin-left: 3.5px;"></i>
                                                            </div>
                                                        </a>

                                                    </div>
                                                }

                                            }
                                        }
                                        else
                                        {
                                            <p style="text-align: center; line-height:30px; margin-top: -17.5px;">
                                                <br />
                                                <i class="fas fa-edit" style="font-size:2.95em; margin-left: 3.5px;margin-bottom:13px;"></i>
                                                <br />
                                                Niste još riješili ni jednu lekciju.<br /> Možete to učiniti klikom na gumb <b>Kreni</b>.
                                                <br />
                                                @Html.ActionLink("Kreni", "Igraj", null, new { @class = "btn btn-success", style = "width: 190px; margin-top: 15px;" })
                                            </p>

                                            <div class="clearfix"></div>
                                        }

                                    </div>
                                </div>
                            </div>
                        </div>

                        <style>
                            .panel-collapse {
                                background-color: none;
                                color: #000;
                            }
                        </style>

                    </div>
                </div>
            </div>


        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")

    <script>
        $(".spoiler-trigger").click(function () {
            $(this).parent().next().collapse('toggle');
        });
    </script>

    <style>

        @@media only screen and (max-width: 800px) {
            .body-content {
                padding-left: 0px !important;
                padding-right: 0 !important;
            }

            h2 {
                font-size: 2.2em !important;
                margin-bottom: 25px;
            }

            .lekcijeH {
                margin-right: 0px !important;
            }

            .lekcije {
                margin-top: 8px;
            }

            .container > .navbar-header {
                margin-left: 0;
                margin-right: 0;
            }

            .container {
                padding-left: 0px !important;
                padding-right: 0px !important;
            }

            .lekcijeH {
                margin-left: 0px !important;
            }

            .yes-holder, .no-holder {
                margin-top: 5.5px !important;
            }
        }

        .col-sm-12 {
            padding-left: 0;
            padding-right: 0;
        }

        .panel-default {
            -moz-border-radius: 0px;
            -webkit-border-radius: 0px;
            border-radius: 0px;
            width: 100%;
        }


        .lekcijeH {
            margin-left: 5px;
        }

        #logo {
            width: 200px;
            padding: 30px;
            -moz-border-radius: 50%;
            -webkit-border-radius: 50%;
            border-radius: 50%;
            background-color: white;
        }

        .-holder {
            border: 1px solid #ccc;
            background-color: rgba(255, 255, 255, 0.40);
        }

        .yes-holder {
            border: 1px solid #ccc;
            background-color: rgba(115, 217, 56, 0.51);
            font-family: 'Roboto Slab';
        }

        .no-holder {
            border: 1px solid #ccc;
            background-color: rgba(111, 202, 255, 0.34);
            font-family: 'Roboto Slab';
        }


        .profile-holder {
            border: 1px solid #ccc;
            background-color: rgba(255, 255, 255, 0.20);
            font-family: 'Roboto Slab';
        }

        .trenutna-lekcija-holder {
            border: 1px solid #ccc;
            background-color: rgba(255, 255, 255, 0.20);
            font-family: 'Roboto Slab';
        }

        #igracLik {
            border: 2px solid #fff;
            width: 70px;
            display: inline-block;
            vertical-align: top;
            margin: 5px;
            -moz-border-radius: 50%;
            -webkit-border-radius: 50%;
            border-radius: 50%;
        }

        .lekcije {
            font-family: 'Roboto Slab';
            padding: 0;
        }

        .panel-default {
            background-color: rgba(199, 199, 199, 0.25) !important;
        }

        .panel-body {
            color: #fff !important;
        }

        .panel-default > .panel-heading {
            background-color: rgba(199, 199, 199, 0.45) !important;
        }
    </style>

    <style>
        header {
            font-family: 'Lobster', cursive;
            text-align: center;
            font-size: 25px;
        }

        #info {
            font-size: 18px;
            color: #555;
            text-align: center;
            margin-bottom: 25px;
        }

        a {
            color: #074E8C;
        }
    </style>